### ISSUE TITLE
Save woff and css with action

### ISSUE THREAD

**Issue by mbtools** [abapGit/icon-font#11]
Can we add something like this to test-build.yml (similar to https://github.com/abapGit/abapGit/blob/master/.github/workflows/build.yml)?

```yml
    - name: Upload font and css 
      if: always()
      uses: actions/upload-artifact@main
      with:
        name: ag-icons.woff
        path: ./build/ag-icons.woff
        name: ag-icons.css
        path: ./build/ag-icons.css
        retention-days: 7
```

This way we won't need to setup our own nodejs etc. 

PS: Not sure if my syntax is correct.
